apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-api
  labels:
    app: match-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: match-api
  template:
    metadata:
      labels:
        app: match-api
    spec:
      containers:
      - name: match-api
        image: jschool/match-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
